version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: tb-timescaledb
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: thingsboard
      PGDATA: /var/lib/postgresql/data/pgdata
    command: postgres -c shared_preload_libraries=pg_stat_statements,timescaledb
    ports:
      - "${TB_DB_PORT:-5432}:5432"
    volumes:
      - ./timescale_data:/var/lib/postgresql/data
