version: '3.8'

services:
  kabiPayment:
    image: piltismartsolutions/thingsboard-3.8.1:v-4.1.2
    container_name: Thingsboard-test
    ports:
      - "80:80"
      - "1883:1883"
      - "7070:7070"
    env_file:
      - ./.tb.env
    restart: always
