version: '3.8'
services:
  pulseX:
    image: piltismartsolutions/pilticloud:v8.4.41
    container_name: pulseX
    ports:
      - "${PULSEX_PORT:-8088}:80"
    env_file:
      - ./.pmx.env
#    working_dir: /app
#    volumes:
#      - ./logs:/app/logs
    restart: always
